services:
  db-auth:
    container_name: db-auth
    image: postgres:latest
    env_file:
      - .env
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - "./schema.sql:/docker-entrypoint-initdb.d/init.sql"
    networks:
      - payetonkawa-n
  
  auth:
    container_name: auth
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    environment:
      - ENV=production
    ports:
      - "8081:8080"
    networks:
      - payetonkawa-n

volumes:
  postgres_data:

networks:
  payetonkawa-n:
    external: true