services:
  db-auth:
    container_name: db-auth
    image: postgres:latest
    env_file:
      - ../auth/.env
    volumes:
      - db-auth-data:/var/lib/postgresql/data
      - "../auth/schema.sql:/docker-entrypoint-initdb.d/init.sql"
    networks:
      - payetonkawa-n
  
  auth:
    container_name: auth
    build:
      context: ../auth
      dockerfile: Dockerfile
    env_file:
      - ../auth/.env
    environment:
      - ENV=production
    networks:
      - payetonkawa-n

volumes:
  db-auth-data:

networks:
  payetonkawa-n:
    external: true