openapi: 3.0.1
info:
  title: Authentication Service
  description: This service handles user authentication including login, token refresh, and token verification.
  version: "1.0.0"
servers:
  - url: 'http://localhost:8080/'
paths:
  /login:
    post:
      summary: User login
      description: Authenticates a user and returns access and refresh tokens.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UserCredentials'
      responses:
        '200':
          description: Successful login
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TokenDetails'
        '400':
          description: Bad request
        '401':
          description: Unauthorized
        '500':
          description: Internal server error
  /refresh:
    post:
      summary: Refresh access token
      description: Refreshes access and refresh tokens using a valid refresh token.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - refresh_token
              properties:
                refresh_token:
                  type: string
      responses:
        '200':
          description: Tokens refreshed successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TokenDetails'
        '400':
          description: Bad request
        '401':
          description: Unauthorized
        '500':
          description: Internal server error
  /verify:
    post:
      summary: Verify access token
      description: Verifies the validity of an access token and returns the user ID.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - access_token
              properties:
                access_token:
                  type: string
      responses:
        '200':
          description: Access token is valid
          content:
            application/json:
              schema:
                type: object
                properties:
                  user_id:
                    type: string
        '400':
          description: Bad request
        '401':
          description: Unauthorized
components:
  schemas:
    UserCredentials:
      type: object
      required:
        - email
        - password
      properties:
        email:
          type: string
        password:
          type: string
    TokenDetails:
      type: object
      properties:
        access_token:
          type: string
        refresh_token:
          type: string
        at_expires:
          type: integer
          format: int64
        rt_expires:
          type: integer
          format: int64
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
security:
  - bearerAuth: []
