apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: payetonkawa-certificate
  namespace: payetonkawa-prod
spec:
  secretName: payetonkawa-tls
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  dnsNames:
    - payetonkawa.germainleignel.com