apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth-service
  template:
    metadata:
      labels:
        app: auth-service
    spec:
      containers:
      - name: auth-container
        image: registry.germainleignel.com/paye-ton-kawa/auth:latest
        ports:
        - containerPort: 8081
        envFrom:
        - secretRef:
            name: auth-secrets