apiVersion: v1
kind: Service
metadata:
  name: postgres-auth-service
  namespace: payetonkawa-prod
spec:
  selector:
    app: postgres
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432
  type: ClusterIP
