apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-deployment
  namespace: {{ .Values.namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth-service
  template:
    metadata:
      labels:
        app: auth-service
    spec:
      containers:
      - name: auth-container
        image: {{ .Values.auth.image }}
        ports:
        - containerPort: 8081
        envFrom:
        - secretRef:
            name: auth-secrets
        env:
        - name: ENV
          value: {{ .Values.auth.env.ENV }}
        - name: DB_HOST
          value: {{ .Values.auth.env.DB_HOST }}
        - name: KAFKA_HOST
          value: {{ .Values.auth.env.KAFKA_HOST }}
        resources:
          limits:
            cpu: "1"
            memory: "512Mi"
          requests:
            cpu: "100m"
            memory: "256Mi"
